# Generated by Django 4.2.18 on 2025-03-19 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("conversation", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="title",
        ),
        migrations.AlterField(
            model_name="message",
            name="content_type",
            field=models.ForeignKey(
                limit_choices_to={"model__in": ["user"]},
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
    ]
