# Generated by Django 4.2.18 on 2025-03-28 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("conversation", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chat",
            options={"get_latest_by": "created_date", "ordering": ("created_date",)},
        ),
    ]
