# Generated by Django 4.2.18 on 2025-03-19 21:53

from django.db import migrations, models
import django.db.models.deletion
import domain.apps.system.models.attachment
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(
                        max_length=255,
                        upload_to=domain.apps.system.models.attachment.upload_to,
                    ),
                ),
                (
                    "file_type",
                    models.CharField(choices=[("Image", "Image")], max_length=10),
                ),
                (
                    "object_id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_date",),
                "get_latest_by": "created_date",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="system_atta_content_993caf_idx",
                    )
                ],
            },
        ),
    ]
