# Generated by Django 4.2.18 on 2025-03-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="object_id",
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
